name = "High Contrast"
description = "Maximum accessibility colors"

[colors]
background_color = "0, 0, 0"
accent_color = "255, 255, 0"
accent_color_text = "0, 0, 0"
text_color = "255, 255, 255"
link_color = "0, 255, 255"
alt_color = "255, 0, 0"
button_background_color_1 = "255, 255, 255"
button_background_color_2 = "255, 255, 0"
button_background_color_3 = "0, 255, 0"
button_text_color = "0, 0, 0"
