name = "Crimson Night"
description = "Dark red passionate"

[colors]
background_color = "35, 15, 15"
accent_color = "220, 20, 60"
accent_color_text = "255, 255, 255"
text_color = "255, 240, 245"
link_color = "255, 99, 71"
alt_color = "255, 215, 0"
button_background_color_1 = "178, 34, 34"
button_background_color_2 = "139, 0, 0"
button_background_color_3 = "205, 92, 92"
button_text_color = "255, 255, 255"
