name = "Golden Sand"
description = "Bright warm yellows"

[colors]
background_color = "255, 253, 240"
accent_color = "184, 134, 11"
accent_color_text = "255, 255, 255"
text_color = "101, 63, 13"
link_color = "146, 64, 14"
alt_color = "34, 139, 34"
button_background_color_1 = "218, 165, 32"
button_background_color_2 = "205, 133, 63"
button_background_color_3 = "210, 180, 140"
button_text_color = "119, 59, 12"
