name = "Cyber Neon"
description = "Bright electric colors"

[colors]
background_color = "12, 12, 12"
accent_color = "0, 255, 127"
accent_color_text = "0, 0, 0"
text_color = "0, 255, 0"
link_color = "0, 255, 255"
alt_color = "255, 0, 255"
button_background_color_1 = "0, 240, 240"
button_background_color_2 = "88, 230, 212"
button_background_color_3 = "90, 225, 50"
button_text_color = "0, 0, 0"
