name = "Purple Haze"
description = "Deep violet atmosphere"

[colors]
background_color = "45, 25, 55"
accent_color = "147, 112, 219"
accent_color_text = "255, 255, 255"
text_color = "248, 248, 255"
link_color = "186, 85, 211"
alt_color = "255, 20, 147"
button_background_color_1 = "138, 43, 226"
button_background_color_2 = "75, 0, 130"
button_background_color_3 = "106, 90, 205"
button_text_color = "255, 255, 255"
