name = "Sunset Glow"
description = "Warm orange golden hues"

[colors]
background_color = "54, 34, 24"
accent_color = "255, 69, 0"
accent_color_text = "255, 255, 255"
text_color = "255, 248, 220"
link_color = "255, 140, 0"
alt_color = "255, 215, 0"
button_background_color_1 = "205, 85, 65"
button_background_color_2 = "210, 115, 25"
button_background_color_3 = "200, 130, 35"
button_text_color = "255, 255, 255"
